const PRODUCT_DETAIL_REQUEST = '@productDetail/PRODUCT_DETAIL_REQUEST';
const PRODUCT_DETAIL_SUCCESS = '@productDetail/PRODUCT_DETAIL_SUCCESS';
const PRODUCT_DETAIL_FAILED = '@productDetail/PRODUCT_DETAIL_FAILED';

export { PRODUCT_DETAIL_REQUEST, PRODUCT_DETAIL_SUCCESS, PRODUCT_DETAIL_FAILED }