const SEARCHING_REQUEST = '@searching/SEARCHING_REQUEST';
const SEARCHING_SUCCESS = '@searching/SEARCHING_SUCCESS';
const SEARCHING_FAILED = '@searching/SEARCHING_FAILED';

export { SEARCHING_REQUEST, SEARCHING_SUCCESS, SEARCHING_FAILED }