const JOB_DETAIL_REQUEST = '@jobDetail/JOB_DETAIL_REQUEST';
const JOB_DETAIL_SUCCESS = '@jobDetail/JOB_DETAIL_SUCCESS';
const JOB_DETAIL_FAILED = '@jobDetail/JOB_DETAIL_FAILED';

const LIST_COMMENT_REQUEST = '@listComment/LIST_COMMENT_REQUEST';
const LIST_COMMENT_SUCCESS = '@listComment/LIST_COMMENT_SUCCESS';
const LIST_COMMENT_FAILED = '@listComment/LIST_COMMENT_FAILED';

const COMMENT_REQUEST = '@comment/COMMENT_REQUEST';
const COMMENT_SUCCESS = '@comment/COMMENT_SUCCESS';
const COMMENT_FAILED = '@comment/COMMENT_FAILED';

const ORDER_JOB_REQUEST = '@orderJob/ORDER_JOB_REQUEST';
const ORDER_JOB_SUCCESS = '@orderJob/ORDER_JOB_SUCCESS';
const ORDER_JOB_FAILED = '@orderJob/ORDER_JOB_FAILED';

export { JOB_DETAIL_REQUEST, JOB_DETAIL_SUCCESS, JOB_DETAIL_FAILED, LIST_COMMENT_REQUEST, LIST_COMMENT_SUCCESS, LIST_COMMENT_FAILED, COMMENT_REQUEST, COMMENT_SUCCESS, COMMENT_FAILED, ORDER_JOB_REQUEST, ORDER_JOB_SUCCESS, ORDER_JOB_FAILED }