const JOB_TYPES_REQUEST = '@jobTypes/JOB_TYPES_REQUEST';
const JOB_TYPES_SUCCESS = '@jobTypes/JOB_TYPES_SUCCESS';
const JOB_TYPES_FAILED = '@jobTypes/JOB_TYPES_FAILED';

export { JOB_TYPES_REQUEST, JOB_TYPES_SUCCESS, JOB_TYPES_FAILED }