const CART_MANAGEMENT_REQUEST = '@productsManagement/CART_MANAGEMENT_REQUEST';
const CART_MANAGEMENT_SUCCESS = '@productsManagement/CART_MANAGEMENT_SUCCESS';
const CART_MANAGEMENT_FAILED = '@productsManagement/CART_MANAGEMENT_FAILED';

const PRODUCTS_MANAGEMENT_REQUEST = '@cartsManagement/PRODUCTS_MANAGEMENT_REQUEST';
const PRODUCTS_MANAGEMENT_SUCCESS = '@cartsManagement/PRODUCTS_MANAGEMENT_SUCCESS';
const PRODUCTS_MANAGEMENT_FAILED = '@cartsManagement/PRODUCTS_MANAGEMENT_FAILED';

export { CART_MANAGEMENT_REQUEST, CART_MANAGEMENT_SUCCESS, CART_MANAGEMENT_FAILED, PRODUCTS_MANAGEMENT_REQUEST, PRODUCTS_MANAGEMENT_SUCCESS, PRODUCTS_MANAGEMENT_FAILED}