const CART_MANAGEMENT_REQUEST = '@productsManagement/CART_MANAGEMENT_REQUEST';
const CART_MANAGEMENT_SUCCESS = '@productsManagement/CART_MANAGEMENT_SUCCESS';
const CART_MANAGEMENT_FAILED = '@productsManagement/CART_MANAGEMENT_FAILED';

export { CART_MANAGEMENT_REQUEST, CART_MANAGEMENT_SUCCESS, CART_MANAGEMENT_FAILED }